spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/voting_session_db
    #    username: postgres
    #    password: 1nd1c4
    username: newparus
    password: n3wp@rus
    driver-class-name: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create" after update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  data:
    rest:
      basePath: "/api"
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
